Kaolisle_Hotel_4F_MapScripts::
	.byte 0


Room401::
	msgbox Room401_Text_0, MSGBOX_SIGN
	end


Room402::
	msgbox Room402_Text_0, MSGBOX_SIGN
	end


Room403::
	msgbox Room403_Text_0, MSGBOX_SIGN
	end


Room404::
	msgbox Room404_Text_0, MSGBOX_SIGN
	end


Room401_Text_0:
	.string "Room 401$"

Room402_Text_0:
	.string "Room 402$"

Room403_Text_0:
	.string "Room 403$"

Room404_Text_0:
	.string "Room 404: Reservation not found$"
