#ifndef GUARD_CONSTANTS_BATTLE_SETUP_H
#define GUARD_CONSTANTS_BATTLE_SETUP_H

#define TRAINER_BATTLE_SINGLE                           0
#define TRAINER_BATTLE_CONTINUE_SCRIPT_NO_MUSIC         1
#define TRAINER_BATTLE_CONTINUE_SCRIPT                  2
#define TRAINER_BATTLE_SINGLE_NO_INTRO_TEXT             3
#define TRAINER_BATTLE_DOUBLE                           4
#define TRAINER_BATTLE_REMATCH                          5
#define TRAINER_BATTLE_CONTINUE_SCRIPT_DOUBLE           6
#define TRAINER_BATTLE_REMATCH_DOUBLE                   7
#define TRAINER_BATTLE_CONTINUE_SCRIPT_DOUBLE_NO_MUSIC  8
#define TRAINER_BATTLE_TWO_TRAINERS_NO_INTRO            13
#define TRAINER_BATTLE_EARLY_RIVAL                      14

enum ScriptedBattleType
{
    SCRIPTED_BATTLE_TYPE_NORMAL,
    SCRIPTED_BATTLE_TYPE_GHOST,
    SCRIPTED_BATTLE_TYPE_GROTTO,
    SCRIPTED_BATTLE_TYPE_MON_WITHOUT_TRAINER,
    SCRIPTED_BATTLE_TYPE_NO_RUNNING,
    SCRIPTED_BATTLE_TYPE_HONEY_TREE,
};

#endif // GUARD_CONSTANTS_BATTLE_SETUP_H
