#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    HEAL_LOCATION_PETALBURG_CITY,
    HEAL_LOCATION_SLATEPORT_CITY,
    HEAL_LOCATION_MAUVILLE_CITY,
    HEAL_LOCATION_RUSTBORO_CITY,
    HEAL_LOCATION_FORTREE_CITY,
    HEAL_LOCATION_LILYCOVE_CITY,
    HEAL_LOCATION_MOSSDEEP_CITY,
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    HEAL_LOCATION_EVER_GRANDE_CITY,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE,
    HEAL_LOCATION_OLDALE_TOWN,
    HEAL_LOCATION_DEWFORD_TOWN,
    HEAL_LOCATION_LAVARIDGE_TOWN,
    HEAL_LOCATION_FALLARBOR_TOWN,
    HEAL_LOCATION_VERDANTURF_TOWN,
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    HEAL_LOCATION_PEARLWOOD_POINT,
    HEAL_LOCATION_PRIMROSE_TOWN,
    HEAL_LOCATION_CORALGROVE_CITY,
    HEAL_LOCATION_PLAYER_HOUSE2F,
    HEAL_LOCATION_COAST_TOWN,
    HEAL_LOCATION_ALDELEAF_CITY,
    HEAL_LOCATION_SKYLOCH_VILLAGE,
    HEAL_LOCATION_SHORESLATE_CITY,
    HEAL_LOCATION_MARIGORGE_TOWN,
    HEAL_LOCATION_KAOLISLE_CITY,
    HEAL_LOCATION_ROCKLIFFE_TOWN,
    HEAL_LOCATION_SANDSTONE_CITY,
    HEAL_LOCATION_FISHING_VILLAGE,
    HEAL_LOCATION_DRISLEDGE_TOWN,
    HEAL_LOCATION_FISH_VILLAGE_FILLER,
    HEAL_LOCATION_AMBEROCK_TOWN,
    HEAL_LOCATION_BASALUFF_TOWN,
    HEAL_LOCATION_EVERFROST_TOWN,
    HEAL_LOCATION_FROSTFIRE_CITY,
    HEAL_LOCATION_CRYSTALPINE_TWON,
    HEAL_LOCATION_ICEPERCH_CITY,
    HEAL_LOCATION_SNOWCREST_CITY,
    HEAL_LOCATION_GALEWIND_CITY,
    HEAL_LOCATION_SANDSTONE_CITY_ALT,
    HEAL_LOCATION_SNOWCREST_CITY_PART2,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
