#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_RoutesAndSideAreas
#define MAP_NEW_ROUTE101                     (0 | (0 << 8))
#define MAP_ROUTE2                           (1 | (0 << 8))
#define MAP_COAST1                           (2 | (0 << 8))
#define MAP_ROUTE3                           (3 | (0 << 8))
#define MAP_ROUTE5                           (4 | (0 << 8))
#define MAP_ROUTE6                           (5 | (0 << 8))
#define MAP_ROUTE7                           (6 | (0 << 8))
#define MAP_ROUTE7_GROTTO                    (7 | (0 << 8))
#define MAP_ROUTE8                           (8 | (0 << 8))
#define MAP_ROUTE9                           (9 | (0 << 8))
#define MAP_ROUTE10                          (10 | (0 << 8))
#define MAP_ROUTE11                          (11 | (0 << 8))
#define MAP_ROUTE12                          (12 | (0 << 8))
#define MAP_ROUTE13                          (13 | (0 << 8))
#define MAP_ROUTE14                          (14 | (0 << 8))
#define MAP_ROUTE28                          (15 | (0 << 8))
#define MAP_ROUTE28TUNNEL_HOUSE              (16 | (0 << 8))
#define MAP_PRIMROSE_MEADOW                  (17 | (0 << 8))
#define MAP_WINDY_WOODS                      (18 | (0 << 8))
#define MAP_LOST_GLADE                       (19 | (0 << 8))
#define MAP_WW_GROTTO                        (20 | (0 << 8))
#define MAP_POKE_RANCH                       (21 | (0 << 8))
#define MAP_RANCH_BARN                       (22 | (0 << 8))
#define MAP_RANCH_HOUSE                      (23 | (0 << 8))
#define MAP_WINDPLUME_RIDGE                  (24 | (0 << 8))
#define MAP_WEIRD_CAVE                       (25 | (0 << 8))
#define MAP_WEIRD_CAVE_PT2                   (26 | (0 << 8))
#define MAP_DESERT                           (27 | (0 << 8))
#define MAP_UNDERGROUND_RUINS                (28 | (0 << 8))
#define MAP_UNDERGROUND_RUINS_1F             (29 | (0 << 8))
#define MAP_UNDERGROUND_RUINS_3F             (30 | (0 << 8))
#define MAP_UNDERGROUND_RUINS_VOLCARONA_ROOM (31 | (0 << 8))
#define MAP_ROUTE11_CAVE                     (32 | (0 << 8))
#define MAP_FLOODED_CAVE1F                   (33 | (0 << 8))
#define MAP_FLOODED_CAVE2F                   (34 | (0 << 8))
#define MAP_FLOODED_CAVE3F                   (35 | (0 << 8))
#define MAP_ROUTE12_SIDE_AREA                (36 | (0 << 8))
#define MAP_ROUTE12_STRENGTH_HOUSE           (37 | (0 << 8))
#define MAP_ADAMANT_TOWER_EXTERIOR           (38 | (0 << 8))
#define MAP_SKY_PILLAR_1F                    (39 | (0 << 8))
#define MAP_SKY_PILLAR_2F                    (40 | (0 << 8))
#define MAP_SKY_PILLAR_3F                    (41 | (0 << 8))
#define MAP_SKY_PILLAR_4F                    (42 | (0 << 8))
#define MAP_SKY_PILLAR_5F                    (43 | (0 << 8))
#define MAP_UNDERGROUND_RUINS_4F             (44 | (0 << 8))
#define MAP_ROUTE15                          (45 | (0 << 8))
#define MAP_WINDPLUME_PEAK                   (46 | (0 << 8))
#define MAP_ROUTE10_CAVE1                    (47 | (0 << 8))
#define MAP_ROUTE10_CAVE2                    (48 | (0 << 8))
#define MAP_BERRY_FIELDS                     (49 | (0 << 8))
#define MAP_ROUTE23                          (50 | (0 << 8))
#define MAP_DRISLEDGE_TOWN                   (51 | (0 << 8))
#define MAP_ROUTE22                          (52 | (0 << 8))
#define MAP_ROUTE14_GROTTO                   (53 | (0 << 8))
#define MAP_BERRY_FIELD_HOUSE                (54 | (0 << 8))
#define MAP_ROUTE15_MOVE_REMINDER            (55 | (0 << 8))
#define MAP_MT_CHIMNEY                       (56 | (0 << 8))

// gMapGroup_TownsAndCities
#define MAP_PEARLWOOD_POINT     (0 | (1 << 8))
#define MAP_PRIMROSE_TOWN       (1 | (1 << 8))
#define MAP_CORALGROVE_CITY     (2 | (1 << 8))
#define MAP_CORALGROVE_HARBOR   (3 | (1 << 8))
#define MAP_COAST_TOWN          (4 | (1 << 8))
#define MAP_WIP_CITY1           (5 | (1 << 8))
#define MAP_TOWN_WIP2           (6 | (1 << 8))
#define MAP_SHORESLATE_CITY     (7 | (1 << 8))
#define MAP_MARIGORGE_TOWN      (8 | (1 << 8))
#define MAP_KAOLISLE_CITY       (9 | (1 << 8))
#define MAP_ROCKLIFFE_TOWN      (10 | (1 << 8))
#define MAP_SANDSTONE_CITY      (11 | (1 << 8))
#define MAP_FISHING_VILLAGE     (12 | (1 << 8))
#define MAP_FISH_VILLAGE_FILLER (13 | (1 << 8))
#define MAP_AMBEROCK_TOWN       (14 | (1 << 8))

// gMapGroup_IndoorPearlwoodPoint
#define MAP_LAB2                   (0 | (2 << 8))
#define MAP_PLAYER_HOUSE1F         (1 | (2 << 8))
#define MAP_PLAYER_HOUSE2F         (2 | (2 << 8))
#define MAP_PEARLWOOD_MAYS_HOUSE1F (3 | (2 << 8))
#define MAP_PEARLWOOD_MAYS_HOUSE2F (4 | (2 << 8))
#define MAP_PEARLWOOD_HOUSE1       (5 | (2 << 8))
#define MAP_PEARLWOOD_HOUSE2       (6 | (2 << 8))
#define MAP_PEARLWOOD_HOUSE2_2F    (7 | (2 << 8))
#define MAP_PEARLWOOD_HOUSE3       (8 | (2 << 8))
#define MAP_PLAYER_HOUSE2F_MAY     (9 | (2 << 8))
#define MAP_PLAYER_HOUSE1F_MAY     (10 | (2 << 8))
#define MAP_RIVAL_HOUSE1F_BRENDAN  (11 | (2 << 8))
#define MAP_RIVAL_HOUSE2F_BRENDAN  (12 | (2 << 8))

// gMapGroup_IndoorPrimroseTown
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (0 | (3 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (1 | (3 << 8))
#define MAP_OLDALE_TOWN_HOUSE1            (2 | (3 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (3 | (3 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (3 << 8))

// gMapGroup_IndoorCoralgroveCity
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (0 | (4 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (1 | (4 << 8))
#define MAP_CORAL_TRADE_HOUSE               (2 | (4 << 8))
#define MAP_CORALGROVE_FRIENDSHIP_RATER     (3 | (4 << 8))
#define MAP_SCHOOL_HALL                     (4 | (4 << 8))
#define MAP_SCHOOL_HALL2F                   (5 | (4 << 8))
#define MAP_CORALGROVE_SHOP                 (6 | (4 << 8))
#define MAP_NEW_CORALGROVE_CITY_GYM         (7 | (4 << 8))
#define MAP_RUSTBORO_CITY_MART              (8 | (4 << 8))
#define MAP_CORALGROVE_ELEVATOR1            (9 | (4 << 8))
#define MAP_CORALGROVE_ELEVATOR2            (10 | (4 << 8))
#define MAP_CORALGROVE_ELEVATOR_INT         (11 | (4 << 8))
#define MAP_CORALGROVE_ELEVATOR_INT2        (12 | (4 << 8))
#define MAP_CORALGROVE_HARVOR_INTERIOR      (13 | (4 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE           (14 | (4 << 8))
#define MAP_CORAL_HARBOR_HOUSE              (15 | (4 << 8))

// gMapGroup_IndoorAzuretideTown
#define MAP_COAST_TOWN_HARBOR                      (0 | (5 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F         (1 | (5 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F         (2 | (5 << 8))
#define MAP_SLATEPORT_CITY_MART                    (3 | (5 << 8))
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (4 | (5 << 8))
#define MAP_AZURETIDE_HOUSE1                       (5 | (5 << 8))
#define MAP_AZURETIDE_HOUSE2                       (6 | (5 << 8))
#define MAP_AZURETIDE_MART                         (7 | (5 << 8))

// gMapGroup_IndoorAldeleafCity
#define MAP_ALDELEAF_SMALL_HOUSE1            (0 | (6 << 8))
#define MAP_ALDELEAF_SMALL_HOUSE2            (1 | (6 << 8))
#define MAP_ALDELEAF_SMALL_HOUSE3            (2 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE1              (3 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE1_2F           (4 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE2              (5 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE2_2F           (6 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE3              (7 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE3_2F           (8 | (6 << 8))
#define MAP_ALDELEAF_BIG_HOUSE3_3F           (9 | (6 << 8))
#define MAP_ALDELEAF_POKE_CENTER1F           (10 | (6 << 8))
#define MAP_ALDELEAF_POKE_CENTER2F           (11 | (6 << 8))
#define MAP_ALDELEAF_MART                    (12 | (6 << 8))
#define MAP_ALDELEAF_BPSHOP                  (13 | (6 << 8))
#define MAP_ALDELEAF_GYM                     (14 | (6 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F (15 | (6 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F (16 | (6 << 8))

// gMapGroup_IndoorSkylochVillage
#define MAP_SKYLOCH_HOUSE1 (0 | (7 << 8))
#define MAP_SKYLOCH_HOUSE2 (1 | (7 << 8))
#define MAP_SKYLOCH_HOUSE3 (2 | (7 << 8))
#define MAP_SKYLOCH_HOUSE4 (3 | (7 << 8))

// gMapGroup_IndoorShoreslateCity
#define MAP_SHORESLATE_POKECENTER_1F    (0 | (8 << 8))
#define MAP_SHORESLATE_POKECENTER_2F    (1 | (8 << 8))
#define MAP_SHORESLATE_MART             (2 | (8 << 8))
#define MAP_SHORESLATE_BP_SHOP          (3 | (8 << 8))
#define MAP_SHORESLATE_HARBOR           (4 | (8 << 8))
#define MAP_SHORESLATE_BIKE_SHOP        (5 | (8 << 8))
#define MAP_SHORESLATE_HOUSE1           (6 | (8 << 8))
#define MAP_SHORESLATE_HOUSE2           (7 | (8 << 8))
#define MAP_SHORESLATE_HOUSE3_1F        (8 | (8 << 8))
#define MAP_SHORESLATE_HOUSE3_2F        (9 | (8 << 8))
#define MAP_SHORESLATE_HOUSE3_3F        (10 | (8 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F (11 | (8 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F (12 | (8 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F (13 | (8 << 8))
#define MAP_DEVON_CORP_BASEMENT         (14 | (8 << 8))

// gMapGroup_IndoorMarigorgeTown
#define MAP_MARIGORGE_MART          (0 | (9 << 8))
#define MAP_MARIGORGE_POKECENTER_1F (1 | (9 << 8))
#define MAP_MARIGORGE_POKECENTER_2F (2 | (9 << 8))
#define MAP_MARIGORGE_SMALL_HOUSE1  (3 | (9 << 8))
#define MAP_MARIGORGE_SMALL_HOUSE2  (4 | (9 << 8))

// gMapGroup_IndoorKaolisleCity
#define MAP_KAOLISLE_POKECENTER_1F       (0 | (10 << 8))
#define MAP_KAOLISLE_POKECENTER_2F       (1 | (10 << 8))
#define MAP_KAOLISLE_MART                (2 | (10 << 8))
#define MAP_KAOLISLE_BP_SHOP             (3 | (10 << 8))
#define MAP_KAOLISLE_GYM                 (4 | (10 << 8))
#define MAP_KAOLISLE_HARBOR              (5 | (10 << 8))
#define MAP_KAOLISLE_HOUSE1              (6 | (10 << 8))
#define MAP_KAOLISLE_HOUSE2              (7 | (10 << 8))
#define MAP_KAOLISLE_HOUSE3              (8 | (10 << 8))
#define MAP_KAOLISLE_HOUSE4              (9 | (10 << 8))
#define MAP_KAOLISLE_MINES               (10 | (10 << 8))
#define MAP_KAOLISLE_MINES_2F            (11 | (10 << 8))
#define MAP_KAOLISLE_MINES_3F            (12 | (10 << 8))
#define MAP_KAOLISLE_FISHING_ASSOCIATION (13 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_1F            (14 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_2F            (15 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_3F            (16 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_4F            (17 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_5F            (18 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_2F_ROOMS      (19 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_3F_ROOMS      (20 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_4F_ROOMS      (21 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_5F_ROOMS      (22 | (10 << 8))
#define MAP_KAOLISLE_HOTEL_ELEVATOR      (23 | (10 << 8))

// gMapGroup_IndoorRockliffeTown
#define MAP_ROCKLIFFE_HARBOR        (0 | (11 << 8))
#define MAP_ROCKLIFFE_POKECENTER_1F (1 | (11 << 8))
#define MAP_ROCKLIFFE_POKECENTER_2F (2 | (11 << 8))
#define MAP_ROCKLIFFE_MART          (3 | (11 << 8))
#define MAP_ROCKLIFFE_HOUSE1        (4 | (11 << 8))
#define MAP_ROCKLIFFE_HOUSE2        (5 | (11 << 8))
#define MAP_ROCKLIFFE_HOUSE3        (6 | (11 << 8))

// gMapGroup_IndoorSandstoneCity
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (0 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (1 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (2 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (3 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (4 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (5 | (12 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (6 | (12 << 8))
#define MAP_SANDSTONE_POKECENTER_1F                 (7 | (12 << 8))
#define MAP_SANDSTONE_POKECENTER_2F                 (8 | (12 << 8))
#define MAP_SANDSTONE_SMALL_HOUSE1                  (9 | (12 << 8))
#define MAP_SANDSTONE_SMALL_HOUSE2                  (10 | (12 << 8))
#define MAP_SANDSTONE_SMALL_HOUSE3                  (11 | (12 << 8))
#define MAP_SANDSTONE_SMALL_HOUSE4                  (12 | (12 << 8))
#define MAP_SANDSTONE_SMALL_HOUSE5                  (13 | (12 << 8))
#define MAP_SANDSTONE_BP_SHOP                       (14 | (12 << 8))
#define MAP_SANDSTONE_LARGE_HOUSE1_1F               (15 | (12 << 8))
#define MAP_SANDSTONE_LARGE_HOUSE1_2F               (16 | (12 << 8))
#define MAP_SANDSTONE_LARGE_HOUSE2_1F               (17 | (12 << 8))
#define MAP_SANDSTONE_LARGE_HOUSE2_2F               (18 | (12 << 8))
#define MAP_SANDSTONE_LARGE_HOUSE2_3F               (19 | (12 << 8))
#define MAP_SANDSTONE_GYM_1F                        (20 | (12 << 8))
#define MAP_SANDSTONE_GYM_2F                        (21 | (12 << 8))
#define MAP_SANDSTONE_LIBRARY_1F                    (22 | (12 << 8))
#define MAP_SANDSTONE_LIBRARY_2F                    (23 | (12 << 8))

// gMapGroup_IndoorFishingVillage
#define MAP_FISHING_VILLAGE_HOUSE1 (0 | (13 << 8))
#define MAP_FISHING_VILLAGE_HOUSE2 (1 | (13 << 8))
#define MAP_FISHING_VILLAGE_HOUSE3 (2 | (13 << 8))

// gMapGroup_IndoorDrisledgeTown
#define MAP_DRISLEDGE_POKECENTER_1F (0 | (14 << 8))
#define MAP_DRISLEDGE_POKECENTER_2F (1 | (14 << 8))
#define MAP_DRISLEDGE_MART          (2 | (14 << 8))
#define MAP_DRISLEDGE_HOUSE1        (3 | (14 << 8))
#define MAP_DRISLEDGE_HOUSE2        (4 | (14 << 8))
#define MAP_DRISLEDGE_GYM           (5 | (14 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (15 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (15 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (15 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (15 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (15 << 8))
#define MAP_NEW_BIRCH_LAB                        (5 | (15 << 8))
#define MAP_TOWN1HOUSE1                          (6 | (15 << 8))

// gMapGroup_IndoorOldale

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1 (0 | (17 << 8))
#define MAP_DEWFORD_TOWN_GYM    (1 | (17 << 8))
#define MAP_DEWFORD_TOWN_HALL   (2 | (17 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2 (3 | (17 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_WIP_TOWN3                        (0 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (1 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (2 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (3 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (4 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (5 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (6 | (18 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (7 | (18 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (19 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (19 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (19 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (19 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (19 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (19 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (19 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (19 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (20 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (20 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (20 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (20 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (20 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (20 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (20 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (20 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (21 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (21 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (22 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (22 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (22 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (22 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (22 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (22 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (22 << 8))
#define MAP_CORALGROVE_GYM                   (7 | (22 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (23 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (23 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (23 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (23 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (23 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (23 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (23 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (23 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (23 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (23 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (23 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (23 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (23 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (24 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (24 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (24 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (24 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (24 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (24 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (24 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (24 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_GYM            (0 | (25 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL (1 | (25 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F       (2 | (25 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F       (3 | (25 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1         (4 | (25 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE  (5 | (25 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2         (6 | (25 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F       (7 | (25 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F       (8 | (25 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F       (9 | (25 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3         (10 | (25 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (26 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (26 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (26 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (26 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (26 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (26 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (26 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (26 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (26 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (26 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F       (0 | (27 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F       (1 | (27 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY            (2 | (27 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL             (3 | (27 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F        (4 | (27 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F        (5 | (27 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART              (6 | (27 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB (7 | (27 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                   (8 | (27 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE      (9 | (27 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                   (10 | (27 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                   (11 | (27 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                   (12 | (27 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                   (13 | (27 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (28 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (28 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (28 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (28 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (28 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (28 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (28 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (28 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (28 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (28 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (28 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (28 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (28 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (29 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (29 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (30 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (30 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (31 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (31 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (32 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (32 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (33 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (33 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (34 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (34 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (34 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (35 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (36 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (37 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (38 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (38 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (38 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (38 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (38 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (38 << 8))
#define MAP_DESERT_RUINS                             (6 | (38 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (38 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (38 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (38 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (38 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (38 << 8))
#define MAP_JAGGED_PASS                              (12 | (38 << 8))
#define MAP_FIERY_PATH                               (13 | (38 << 8))
#define MAP_MT_PYRE_1F                               (14 | (38 << 8))
#define MAP_MT_PYRE_2F                               (15 | (38 << 8))
#define MAP_MT_PYRE_3F                               (16 | (38 << 8))
#define MAP_MT_PYRE_4F                               (17 | (38 << 8))
#define MAP_MT_PYRE_5F                               (18 | (38 << 8))
#define MAP_MT_PYRE_6F                               (19 | (38 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (20 | (38 << 8))
#define MAP_MT_PYRE_SUMMIT                           (21 | (38 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (22 | (38 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (23 | (38 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (24 | (38 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (25 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (26 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (27 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (28 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (29 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (30 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (31 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (32 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (33 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (34 | (38 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (35 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (36 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (37 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (38 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (39 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (40 | (38 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (41 | (38 << 8))
#define MAP_VICTORY_ROAD_1F                          (42 | (38 << 8))
#define MAP_VICTORY_ROAD_B1F                         (43 | (38 << 8))
#define MAP_VICTORY_ROAD_B2F                         (44 | (38 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (45 | (38 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (46 | (38 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (47 | (38 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (48 | (38 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (49 | (38 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (50 | (38 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (51 | (38 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (52 | (38 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (53 | (38 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (54 | (38 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (55 | (38 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (56 | (38 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (57 | (38 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (58 | (38 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (59 | (38 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (60 | (38 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (61 | (38 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (62 | (38 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (63 | (38 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (64 | (38 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (65 | (38 << 8))
#define MAP_ISLAND_CAVE                              (66 | (38 << 8))
#define MAP_ANCIENT_TOMB                             (67 | (38 << 8))
#define MAP_UNDERWATER_ROUTE134                      (68 | (38 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (69 | (38 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (70 | (38 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (71 | (38 << 8))
#define MAP_SCORCHED_SLAB                            (72 | (38 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (73 | (38 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (74 | (38 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (75 | (38 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (76 | (38 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (77 | (38 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (78 | (38 << 8))
#define MAP_SKY_PILLAR_TOP                           (79 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (80 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (81 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (82 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (83 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (84 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (85 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (86 | (38 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (87 | (38 << 8))
#define MAP_MIRAGE_TOWER_1F                          (88 | (38 << 8))
#define MAP_MIRAGE_TOWER_2F                          (89 | (38 << 8))
#define MAP_MIRAGE_TOWER_3F                          (90 | (38 << 8))
#define MAP_MIRAGE_TOWER_4F                          (91 | (38 << 8))
#define MAP_DESERT_UNDERPASS                         (92 | (38 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (93 | (38 << 8))
#define MAP_ARTISAN_CAVE_1F                          (94 | (38 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (95 | (38 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (96 | (38 << 8))
#define MAP_MARINE_CAVE_END                          (97 | (38 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (98 | (38 << 8))
#define MAP_TERRA_CAVE_END                           (99 | (38 << 8))
#define MAP_ALTERING_CAVE                            (100 | (38 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (101 | (38 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (39 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (39 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (39 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (39 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (39 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (39 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (39 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (39 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (39 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (39 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (39 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (39 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (39 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (39 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (39 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (39 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (39 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (39 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (39 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (39 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (39 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (39 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (39 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (39 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (39 << 8))
#define MAP_TRADE_CENTER             (25 | (39 << 8))
#define MAP_RECORD_CORNER            (26 | (39 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (39 << 8))
#define MAP_CONTEST_HALL             (28 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (39 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (39 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (39 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (39 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (39 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (39 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (39 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (39 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (39 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (39 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (39 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (39 << 8))
#define MAP_UNION_ROOM               (60 | (39 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (40 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (40 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (40 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (40 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (40 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (40 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (40 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (40 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (40 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (40 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (40 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (40 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (40 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (40 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (40 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (40 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (40 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (40 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (40 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (40 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (40 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (40 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (40 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (40 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (40 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (40 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (40 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (40 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (40 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (40 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (40 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (40 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (40 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (40 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (40 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (40 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (40 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (40 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (40 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (40 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (40 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (40 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (40 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (41 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (41 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (42 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (43 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (43 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (43 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (43 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (44 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (45 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (46 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (46 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (46 << 8))

// gMapGroup_OldAreas
#define MAP_TEST_ROOM           (0 | (47 << 8))
#define MAP_PETALBURG_CITY      (1 | (47 << 8))
#define MAP_SLATEPORT_CITY      (2 | (47 << 8))
#define MAP_MAUVILLE_CITY       (3 | (47 << 8))
#define MAP_RUSTBORO_CITY       (4 | (47 << 8))
#define MAP_FORTREE_CITY        (5 | (47 << 8))
#define MAP_LILYCOVE_CITY       (6 | (47 << 8))
#define MAP_MOSSDEEP_CITY       (7 | (47 << 8))
#define MAP_SOOTOPOLIS_CITY     (8 | (47 << 8))
#define MAP_EVER_GRANDE_CITY    (9 | (47 << 8))
#define MAP_LITTLEROOT_TOWN     (10 | (47 << 8))
#define MAP_OLDALE_TOWN         (11 | (47 << 8))
#define MAP_DEWFORD_TOWN        (12 | (47 << 8))
#define MAP_LAVARIDGE_TOWN      (13 | (47 << 8))
#define MAP_FALLARBOR_TOWN      (14 | (47 << 8))
#define MAP_VERDANTURF_TOWN     (15 | (47 << 8))
#define MAP_PACIFIDLOG_TOWN     (16 | (47 << 8))
#define MAP_ROUTE101            (17 | (47 << 8))
#define MAP_ROUTE102            (18 | (47 << 8))
#define MAP_ROUTE103            (19 | (47 << 8))
#define MAP_ROUTE104            (20 | (47 << 8))
#define MAP_ROUTE105            (21 | (47 << 8))
#define MAP_ROUTE106            (22 | (47 << 8))
#define MAP_ROUTE107            (23 | (47 << 8))
#define MAP_ROUTE108            (24 | (47 << 8))
#define MAP_ROUTE109            (25 | (47 << 8))
#define MAP_ROUTE110            (26 | (47 << 8))
#define MAP_ROUTE111            (27 | (47 << 8))
#define MAP_ROUTE112            (28 | (47 << 8))
#define MAP_ROUTE113            (29 | (47 << 8))
#define MAP_ROUTE114            (30 | (47 << 8))
#define MAP_ROUTE115            (31 | (47 << 8))
#define MAP_ROUTE116            (32 | (47 << 8))
#define MAP_ROUTE117            (33 | (47 << 8))
#define MAP_ROUTE118            (34 | (47 << 8))
#define MAP_ROUTE119            (35 | (47 << 8))
#define MAP_ROUTE120            (36 | (47 << 8))
#define MAP_ROUTE121            (37 | (47 << 8))
#define MAP_ROUTE122            (38 | (47 << 8))
#define MAP_ROUTE123            (39 | (47 << 8))
#define MAP_ROUTE124            (40 | (47 << 8))
#define MAP_ROUTE125            (41 | (47 << 8))
#define MAP_ROUTE126            (42 | (47 << 8))
#define MAP_ROUTE127            (43 | (47 << 8))
#define MAP_ROUTE128            (44 | (47 << 8))
#define MAP_ROUTE129            (45 | (47 << 8))
#define MAP_ROUTE130            (46 | (47 << 8))
#define MAP_ROUTE131            (47 | (47 << 8))
#define MAP_ROUTE132            (48 | (47 << 8))
#define MAP_ROUTE133            (49 | (47 << 8))
#define MAP_ROUTE134            (50 | (47 << 8))
#define MAP_UNDERWATER_ROUTE124 (51 | (47 << 8))
#define MAP_UNDERWATER_ROUTE126 (52 | (47 << 8))
#define MAP_UNDERWATER_ROUTE127 (53 | (47 << 8))
#define MAP_UNDERWATER_ROUTE128 (54 | (47 << 8))
#define MAP_UNDERWATER_ROUTE129 (55 | (47 << 8))
#define MAP_UNDERWATER_ROUTE105 (56 | (47 << 8))
#define MAP_UNDERWATER_ROUTE125 (57 | (47 << 8))

// gMapGroup_IndoorRoute124

#define MAP_GROUPS_COUNT 49

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
