#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"
#include "constants/opponents_frlg.h"

#define TRAINER_NONE                          0
#define TRAINER_BROTHER_1_PEARLWOOD               1
#define TRAINER_BROTHER_2_ROUTE28              2
#define TRAINER_BROTHER_3_ROUTE28               3
#define TRAINER_BROTHER_4_ROUTE28               4
#define TRAINER_BROTHER_5_FISHINGVILLAGE              5
#define TRAINER_BROTHER_6_ROUTE20               6
#define TRAINER_UNUSED_7_               7
#define TRAINER_UNUSED_8_              8
#define TRAINER_UNUSED_9_               9
#define TRAINER_UNUSED_10_              10
#define TRAINER_UNUSED_11_             11
#define TRAINER_UNUSED_12_              12
#define TRAINER_UNUSED_13_              13
#define TRAINER_UNUSED_14_             14
#define TRAINER_CRYSTALPINE_NURSE              15
#define TRAINER_R1_YOUNGSTER         16
#define TRAINER_R1_FISHER         17
#define TRAINER_R1_BUG_CATCHER         18
#define TRAINER_R1_TUBER         19
#define TRAINER_R1_COOLTRAINER               20
#define TRAINER_R2_FISHER               21
#define TRAINER_R2_LASS         22
#define TRAINER_R2_BLACKBELT              23
#define TRAINER_R2_YOUNGSTER              24
#define TRAINER_R2_SCHOOL_KID_F              25
#define TRAINER_WW_BUGCATCHER         26
#define TRAINER_WW_LADY         27
#define TRAINER_WW_BUGCATCHER_2         28
#define TRAINER_WW_CAMPER                     29
#define TRAINER_WW_LASS                         30
#define TRAINER_WW_YOUNGSTER                       31
#define TRAINER_WW_ACE_TRAINER     32
#define TRAINER_WW_ROCKET       33
#define TRAINER_SCHOOLHALL_1                       34
#define TRAINER_SCHOOLHALL_2                         35
#define TRAINER_SCHOOLHALL_3                        36
#define TRAINER_SCHOOLHALL_4                       37
#define TRAINER_EV_TRAINING_HP                        38
#define TRAINER_EV_TRAINING_ATK                       39
#define TRAINER_EV_TRAINING_DEF                       40
#define TRAINER_EV_TRAINING_SPATK                       41
#define TRAINER_EV_TRAINING_SPDEF                       42
#define TRAINER_EV_TRAINING_SPEED                       43
#define TRAINER_PRIMROSE_NURSE                      44
#define TRAINER_CORALGYM_1                         45
#define TRAINER_CORALGYM_2                       46
#define TRAINER_CORALGYM_3                      47
#define TRAINER_CORALGYM_4                      48
#define TRAINER_CORALGYM_5                      49
#define TRAINER_CORALGYM_6                      50
#define TRAINER_LEADER_AARON               51
#define TRAINER_CORALGROVE_NURSE               52
#define TRAINER_R4_HIKER               53
#define TRAINER_UNUSED_54_               54
#define TRAINER_R4_POKEMANIAC               55
#define TRAINER_R4_BUGCATCHER               56
#define TRAINER_R4_TWINS                       57
#define TRAINER_R16_SWIMMER_M                      58
#define TRAINER_R4_TRIATHLETE                         59
#define TRAINER_R4_CAMPER                       60
#define TRAINER_R4_COOL_F                       61
#define TRAINER_R4_COOL_M                       62
#define TRAINER_R4_BIRDKEEPER                       63
#define TRAINER_R4_YOUNGSTER                      64
#define TRAINER_R4_BIRDKEEPER2                        65
#define TRAINER_R4_LASS                      66
#define TRAINER_R4_YOUNGSTER2                      67
#define TRAINER_R4_TRIATHLETE2                      68
#define TRAINER_RANCH_ROCKET                      69
#define TRAINER_RANCH_ROCKET2                      70
#define TRAINER_ALDELEAF_NURSE                      71
#define TRAINER_ALDEGYM_1                       72
#define TRAINER_ALDEGYM_2                       73
#define TRAINER_ALDEGYM_3                        74
#define TRAINER_ALDEGYM_4                      75
#define TRAINER_ALDEGYM_5                      76
#define TRAINER_ALDEGYM_6                        77
#define TRAINER_ALDEGYM_7                     78
#define TRAINER_ALDEGYM_8                        79
#define TRAINER_ALDEGYM_9                       80
#define TRAINER_ALDEGYM_10                       81
#define TRAINER_ALDELEAF_MANIAC                         82
#define TRAINER_ALDEGYM_11                         83
#define TRAINER_ALDEGYM_12                     84
#define TRAINER_ALDEGYM_13                     85
#define TRAINER_ALDEGYM_14                     86
#define TRAINER_ALDEGYM_15                     87
#define TRAINER_ALDEGYM_16                       88
#define TRAINER_LEADER_VOLKNER                         89
#define TRAINER_WPV_BIRDKEEPER                          90
#define TRAINER_WPV_TRIATH                              91
#define TRAINER_WPV_BATTLEGIRL                          92
#define TRAINER_WPV_CAMPER                              93
#define TRAINER_WPV_BIRDKEEPER2                          94
#define TRAINER_WPV_MANIAC                              95
#define TRAINER_WPV_BIRDKEEPER3                          96
#define TRAINER_WPV_NINJABOY                            97
#define TRAINER_WPV_LASS                                98
#define TRAINER_WPV_TRIATH2                             99
#define TRAINER_WPV_BIRDKEEPER4                         100
#define TRAINER_WPV_BATTLEGIRL2                         101
#define TRAINER_WPV_BIRDKEEPER5                         102
#define TRAINER_WPV_TR14_SKYLA                              103
#define TRAINER_R30_BUGCATCHER                          104
#define TRAINER_R30_HIKER                               105
#define TRAINER_R30_NINJABOY                            106
#define TRAINER_R30_PSYCHIC                             107
#define TRAINER_R5_FISHER                               108
#define TRAINER_R5_BEAUTY                               109
#define TRAINER_R5_YOUNGCOUPLE                          110
#define TRAINER_R5_LASS1                                111
#define TRAINER_R5_POKEFAN_F                            112
#define TRAINER_R5_LASS2                                113
#define TRAINER_R5_GENTLEMAN                            114
#define TRAINER_R5_YOUNGSTER                            115
#define TRAINER_R5_TRIATHLETE                           116
#define TRAINER_R5_RICHBOY                             117
#define TRAINER_R5_KINDLER                               118
#define TRAINER_R5_BUGCATCHER                          119
#define TRAINER_R5_NINJABOY                            120
#define TRAINER_R5_HIKER                               121
#define TRAINER_R5_ACETRAINER                         122
#define TRAINER_R6_RANGER_M                             123
#define TRAINER_R16_SWIMMER_F2                            124
#define TRAINER_R6_CAMPER_F                             125
#define TRAINER_R16_NINJABOY2                            126
#define TRAINER_R6_HIKER                                127
#define TRAINER_R6_CAMPER_M2                            128
#define TRAINER_R6_KINDLER                              129
#define TRAINER_R8_PARASOLLADY                          130
#define TRAINER_R8_SRJR                                 131
#define TRAINER_R8_AROMALADY                            132
#define TRAINER_R8_YOUNGSTER                            133
#define TRAINER_R8_PSYCHIC_F                            134
#define TRAINER_R8_ENTHUSIAST                             135
#define TRAINER_R8_TRIATHLETE_M                         136
#define TRAINER_R8_GENTLEMAN                            137
#define TRAINER_R8_HIKER                                138
#define TRAINER_R8_OLDCOUPLE                           139
#define TRAINER_R8_BIRDKEEPER                          140
#define TRAINER_SHORESLATE_NURSE                            141
#define TRAINER_DC1F_ROCKET_1                               142
#define TRAINER_DC1F_ROCKET_2                               143
#define TRAINER_DC_BASEROCKET_1                             144
#define TRAINER_DC_BASEROCKET_2                             145
#define TRAINER_DC_BASEROCKET_3                             146
#define TRAINER_DC_BASEROCKET_4                             147
#define TRAINER_DC2F_ROCKET_1                               148
#define TRAINER_DC2F_ROCKET_2                               149
#define TRAINER_DC2F_ROCKET_3                               150
#define TRAINER_DC2F_ROCKET_4                               151
#define TRAINER_DC2F_ROCKET_5                               152
#define TRAINER_DC3F_ROCKET_1                               153
#define TRAINER_DC3F_ROCKET_PROTON                          154
#define TRAINER_SHORESLATE_ROCKET                           155
#define TRAINER_DESERT_CAMPER                           156
#define TRAINER_DESERT_CAMPER2                          157
#define TRAINER_DESERT_PICNICKER                        158
#define TRAINER_DESERT_PICNICKER2                       159
#define TRAINER_DESERT_HIKER                            160
#define TRAINER_DESERT_BLACKBELT                        161
#define TRAINER_DESERT_PICNICKER3                       162
#define TRAINER_DESERT_HIKER2                           163
#define TRAINER_DESERT_HIKER3                           164
#define TRAINER_DESERT_KINDLER                    165
#define TRAINER_DESERT_BLACKBELT2                      166
#define TRAINER_DESERT_HIKER4                          167
#define TRAINER_DESERT_PSYCHIC_F                       168
#define TRAINER_DESERT_ACETRAINER                     169
#define TRAINER_R7_CAMPER                               170
#define TRAINER_R7_PICNICKER                            171
#define TRAINER_UNUSED_172_                             172
#define TRAINER_R7_BIRDKEEPER                           173
#define TRAINER_R7_BLACKBELT                            174
#define TRAINER_R7_PICNICKER2                           175
#define TRAINER_R7_FISHERMAN                            176
#define TRAINER_R7_HIKER                                177
#define TRAINER_R7_PARASOLLADY                          178
#define TRAINER_R7_NINJABOY                            179
#define TRAINER_MARIGORGE_NURSE                             180
#define TRAINER_KAOLGYM_CAMPER1                         181
#define TRAINER_KAOLGYM_PICNICKER1                      182
#define TRAINER_KAOLGYM_HIKER1                          183
#define TRAINER_KAOLGYM_CAMPER2                         184
#define TRAINER_KAOLGYM_HIKER2                          185
#define TRAINER_KAOLGYM_HIKER3                          186
#define TRAINER_KAOLGYM_PICNICKER2                      187
#define TRAINER_KAOLGYM_CAMPER3                         188
#define TRAINER_KAOLGYM_PICNICKER3                      189
#define TRAINER_KAOLGYM_HIKER4                         190
#define TRAINER_KAOLGYM_CLAY                                191
#define TRAINER_KM_PICNICKER                            192
#define TRAINER_KM_BLACKBELT                            193
#define TRAINER_KM_CAMPER                               194
#define TRAINER_KM_HIKER                                195
#define TRAINER_KM_HIKER2                                196
#define TRAINER_KM_HIKER3                                197
#define TRAINER_KM_CAMPER2                               198
#define TRAINER_KM_PICNICKER2                            199
#define TRAINER_KM_BLACKBELT2                            200
#define TRAINER_KM_HIKER4                               201
#define TRAINER_BUFFET_1                                    202
#define TRAINER_BUFFET_2                                    203
#define TRAINER_BUFFET_3                                    204
#define TRAINER_BUFFET_4                                    205
#define TRAINER_HOTEL_BIRDKEEPER                            206
#define TRAINER_HOTEL_KID1                                  207
#define TRAINER_HOTEL_KID2                                  208
#define TRAINER_LEADER_KORRINA                              209
#define TRAINER_ROCKLIFFE_NURSE                             210
#define TRAINER_R11_LASS                                211
#define TRAINER_R11_BIRDKEEPER                          212
#define TRAINER_R11_BUGCATCHER                          213
#define TRAINER_R11_NINJABOY                            214
#define TRAINER_R11_POKEMANIAC                          215
#define TRAINER_R11_TRIATHLETE_F                        216
#define TRAINER_R11_HIKER                               217
#define TRAINER_R11_NINJABOY_2                          218
#define TRAINER_R11_NINJABOY_3                          219
#define TRAINER_R11_CYCLER_M                           220
#define TRAINER_R11_BLACKBELT                          221
#define TRAINER_R11_EXPERT                             222
#define TRAINER_R11_PSYCHIC_F                          223
#define TRAINER_R11_ACETRAINER_F                       224
#define TRAINER_UNUSED_225_                          225
#define TRAINER_UNUSED_226_                         226
#define TRAINER_UNUSED_227_                          227
#define TRAINER_UNUSED_228_                    228
#define TRAINER_UNUSED_229_                   229
#define TRAINER_UNUSED_230_                    230
#define TRAINER_UNUSED_231_                              231
#define TRAINER_UNUSED_232_                              232
#define TRAINER_UNUSED_233_                              233
#define TRAINER_UNUSED_234_                        234
#define TRAINER_UNUSED_235_                       235
#define TRAINER_UNUSED_236_                        236
#define TRAINER_R12_TRIATHLETE_F                        237
#define TRAINER_R12_TRIATHLETE_M                        238
#define TRAINER_R12_TRIATHLETE_F2                       239
#define TRAINER_R12_TRIATHLETE_M2                       240
#define TRAINER_R12_TRIATHLETE_M3                       241
#define TRAINER_R12_TRIATHLETE_F3                       242
#define TRAINER_FROSTHEARTH_NURSE                                  243
#define TRAINER_R16_SWIMMER_F                                 244
#define TRAINER_R12_PSYCHIC_M                           245
#define TRAINER_R12_HIKER                              246
#define TRAINER_R12_LASS                               247
#define TRAINER_R12_BUGMANIAC                          248
#define TRAINER_R12_NINJABOY                           249
#define TRAINER_SANDSTONE_NURSE                             250
#define TRAINER_R16_SWIMMER_F3                            251
#define TRAINER_R16_GUITARIST                        252
#define TRAINER_R16_HIKER                               253
#define TRAINER_R16_BEAUTY                           254
#define TRAINER_FC_BLACKBELT                            255
#define TRAINER_FC_BATTLEGIRL                           256
#define TRAINER_FC_CAMPER                               257
#define TRAINER_FC_HIKER                                258
#define TRAINER_R14_RUNNING_F                           259
#define TRAINER_R14_HIKER                               260
#define TRAINER_UNUSED_SIDNEY                                      261
#define TRAINER_UNUSED_PHOEBE                                      262
#define TRAINER_UNUSED_GLACIA                                      263
#define TRAINER_UNUSED_DRAKE                                       264
#define TRAINER_SANDGYM_CYCLISTM1                       265
#define TRAINER_SANDGYM_CYCLISTF1                       266
#define TRAINER_SANDGYM_CYCLISTF2                       267
#define TRAINER_SANDGYM_CYCLISTM2                       268
#define TRAINER_SANDGYM_CYCLISTF3                       269
#define TRAINER_SANDGYM_CYCLISTM3                       270
#define TRAINER_SANDGYM_CYCLISTM4                       271
#define TRAINER_AT_2F_MAN3                              272
#define TRAINER_AT_2F_WOMAN5                            273
#define TRAINER_AT_2F_PSYCHIC                           274
#define TRAINER_AT_2F_MAN5                              275
#define TRAINER_AT_3F_EXPERT_M                          276
#define TRAINER_AT_3F_EXPERT_F                          277
#define TRAINER_AT_3F_HEXMANIAC                         278
#define TRAINER_AT_3F_PSYCHICF                          279
#define TRAINER_AT_4F_BLACKBELT                         280
#define TRAINER_AT_4F_HEXMANIAC                         281
#define TRAINER_AT_4F_LASS                              282
#define TRAINER_AT_4F_YOUNGSTER                         283
#define TRAINER_AT_4F_BATTLEGIRL                        284
#define TRAINER_AT_4F_BLACKBELT2                         285
#define TRAINER_AT_5F_COOLTRAINER_M                         286
#define TRAINER_AT_5F_COOLTRAINER_F                         287
#define TRAINER_R14_PARASOLLADY              288
#define TRAINER_R14_FISHER              289
#define TRAINER_R14_PARASOLLADY2              290
#define TRAINER_R14_NINJABOY              291
#define TRAINER_R14_ROCKER                      292
#define TRAINER_R14_MANIAC                    293
#define TRAINER_R15_BIRDKEEPER                      294
#define TRAINER_R15_RANGERF                    295
#define TRAINER_R15_RANGERM                    296
#define TRAINER_R15_GENTLEMAN                    297
#define TRAINER_R15_NINJABOY1                    298
#define TRAINER_R15_NINJABOY2                    299
#define TRAINER_R15_BUGCATCHER                     300
#define TRAINER_R15_BUGCATCHER2                     301
#define TRAINER_R15_BEAUTY                    302
#define TRAINER_R15_FISHER                    303
#define TRAINER_R15_ACETRAINER_F                    304
#define TRAINER_R15_ACETRAINER_M                    305
#define TRAINER_R15_COOLTRAINER                    306
#define TRAINER_R15_LASS                   307
#define TRAINER_R15_SCIENTIST                   308
#define TRAINER_R15_AROMALADY                   309
#define TRAINER_R15_NINJABOY3                   310
#define TRAINER_R15_BERRYROCKET                   311
#define TRAINER_R23_BREEDER_M                       312
#define TRAINER_R23_MANIAC                    313
#define TRAINER_R23_TWINS                    314
#define TRAINER_R23_BREEDER_F                    315
#define TRAINER_R23_HEXMANIAC_1                    316
#define TRAINER_R23_PSYCHIC_M                    317
#define TRAINER_R23_HEXMANIAC_2                    318
#define TRAINER_R23_TRIATHLETE_F                       319
#define TRAINER_R23_FISHERMAN                        320
#define TRAINER_R23_BATTLEGIRL                       321
#define TRAINER_R23_NINJABOY                        322
#define TRAINER_R23_ACETRAINER                         323
#define TRAINER_DRISLEDGE_NURSE                      324
#define TRAINER_DRISGYM_1                    325
#define TRAINER_DRISGYM_2                      326
#define TRAINER_DRISGYM_3                      327
#define TRAINER_DRISGYM_4                    328
#define TRAINER_DRISGYM_5                    329
#define TRAINER_DRISGYM_6                    330
#define TRAINER_LEADER_ACEROLA                    331
#define TRAINER_LEADER_JASMINE                       332
#define TRAINER_LEADER_JASMINE_2                       333
#define TRAINER_KASEN                       334
#define TRAINER_R3_SWIMMER_F                     335
#define TRAINER_R3_SWIMMER_M                      336
#define TRAINER_R3_SWIMMER_OLDSIS                        337
#define TRAINER_R3_TUBER                      338
#define TRAINER_R3_FISHERMAN                    339
#define TRAINER_R3_LANDSWIMMER_1                         340
#define TRAINER_R3_LANDSWIMMER_2                        341
#define TRAINER_R3_SAILOR                       342
#define TRAINER_R3_SWIMMER_M1                       343
#define TRAINER_R3_SWIMMER_M2                        344
#define TRAINER_R3_SWIMMER_F1                      345
#define TRAINER_R9_SWIMMER_M                    346
#define TRAINER_R9_BLACKBELT                    347
#define TRAINER_R9_BIRDKEEPER                    348
#define TRAINER_R9_BATTLEGIRL                    349
#define TRAINER_R9_SWIMMER_F                      350
#define TRAINER_R9_FISHERMAN                       351
#define TRAINER_R9_HIKER                     352
#define TRAINER_R9_COLLECTOR                  353
#define TRAINER_R9_SWIMMER_M2                  354
#define TRAINER_R9_LANDSWIMMER                  355
#define TRAINER_R10_ACESWIMMER                  356
#define TRAINER_R10_SWIMMER_F1                  357
#define TRAINER_R10_FISHERMAN                   358
#define TRAINER_R10_SWIMMER_M1                     359
#define TRAINER_R10_BLACKBELT                   360
#define TRAINER_R10_HIKER                   361
#define TRAINER_R10_SWIMMER_F2                   362
#define TRAINER_R10_SWIMMER_M2                   363
#define TRAINER_R10_BATTLEGIRL                     364
#define TRAINER_R10_TUBER_M                     365
#define TRAINER_R16_NINJABOY                     366
#define TRAINER_FACTORY_ROCKET_1                     367
#define TRAINER_R16_EXPERT_F                     368
#define TRAINER_FACTORY_ROCKET_2                     369
#define TRAINER_FACTORY_ROCKET_3                     370
#define TRAINER_FACTORY_ROCKET_4                     371
#define TRAINER_FACTORY_ROCKET_5                     372
#define TRAINER_UNUSED_373                     373
#define TRAINER_UNUSED_374                      374
#define TRAINER_FACTORY_ROCKET_PETREL                   375
#define TRAINER_UNUSED_376_                    376
#define TRAINER_UNUSED_377_                     377
#define TRAINER_UNUSED_378_                       378
#define TRAINER_UNUSED_379_                    379
#define TRAINER_UNUSED_380_                    380
#define TRAINER_UNUSED_381_                    381
#define TRAINER_R17_CAMPER_M                    382
#define TRAINER_R17_PICNICKER1                      383
#define TRAINER_R17_PICNICKER2                       384
#define TRAINER_R17_MANIAC                       385
#define TRAINER_R17_SCIENTIST                   386
#define TRAINER_R17_HIKER1                     387
#define TRAINER_R17_HIKER2                   388
#define TRAINER_R17_COOLTRAINER                   389
#define TRAINER_BTUN_HIKER1                   390
#define TRAINER_BTUN_BLACKBELT                   391
#define TRAINER_BTUN_PICNICKER                   392
#define TRAINER_BTUN_FIREBREATHER                   393
#define TRAINER_BTUN_BLACKBELT2                   394
#define TRAINER_BTUN_CAMPERM                   395
#define TRAINER_BTUN_PICNICKER2                   396
#define TRAINER_BTUN_HIKER2                       397
#define TRAINER_BTUN_BEAUTY                       398
#define TRAINER_BTUN_FIREBREATHER2                        399
#define TRAINER_BTUN_HIKER3                        400
#define TRAINER_BTUN_BROCK                       401
#define TRAINER_R18_HIKER1                    402
#define TRAINER_R18_RANGER_M                     403
#define TRAINER_R18_KINDLER                     404
#define TRAINER_R18_HIKER2                       405
#define TRAINER_R18_RANGER_F                    406
#define TRAINER_R18_SCIENTIST                       407
#define TRAINER_R18_POKEMANIAC                     408
#define TRAINER_R18_BREEDER_M                    409
#define TRAINER_R18_ACE_TRAINER_M                    410
#define TRAINER_LEADER_PRYCE                    411
#define TRAINER_LEADER_BLAINE                    412
#define TRAINER_FROSTGYM_HIKER1                        413
#define TRAINER_FROSTGYM_KINDLER1                        414
#define TRAINER_FROSTGYM_SENIOR                        415
#define TRAINER_FROSTGYM_JUNIOR                     416
#define TRAINER_FROSTGYM_RANGER_M                      417
#define TRAINER_FROSTGYM_RANGER_F                        418
#define TRAINER_FROSTGYM_MANIAC                       419
#define TRAINER_FROSTGYM_COLLECTOR                        420
#define TRAINER_FROSTGYM_KINDLER2                       421
#define TRAINER_FROSTGYM_RANGER_F2                       422
#define TRAINER_AZURETIDE_CELEBI                       423
#define TRAINER_KAOLISLE_CELEBI                       424
#define TRAINER_R19_SWIMMER_F                     425
#define TRAINER_R19_SWIMMER_M                       426
#define TRAINER_R19_SWIMMER_M2                     427
#define TRAINER_R19_SWIMMER_COUPLE                        428
#define TRAINER_R19_SWIMMER_F2                       429
#define TRAINER_R19_SWIMMER_M3                     430
#define TRAINER_R19_BLACKBELT                     431
#define TRAINER_R19_HIKER                     432
#define TRAINER_R19_PICNICKER                     433
#define TRAINER_R19_SWIMMER_M4                  434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_MADELINE_2                  437
#define TRAINER_MADELINE_3                  438
#define TRAINER_MADELINE_4                  439
#define TRAINER_MADELINE_5                  440
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY_1                     449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_JENNY_2                     465
#define TRAINER_JENNY_3                     466
#define TRAINER_JENNY_4                     467
#define TRAINER_JENNY_5                     468
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA_1                     474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_DIANA_2                     477
#define TRAINER_DIANA_3                     478
#define TRAINER_DIANA_4                     479
#define TRAINER_DIANA_5                     480
#define TRAINER_AMY_AND_LIV_1               481
#define TRAINER_AMY_AND_LIV_2               482
#define TRAINER_GINA_AND_MIA_1              483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_AMY_AND_LIV_3               485
#define TRAINER_GINA_AND_MIA_2              486
#define TRAINER_AMY_AND_LIV_4               487
#define TRAINER_AMY_AND_LIV_5               488
#define TRAINER_AMY_AND_LIV_6               489
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST_1                    492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ERNEST_2                    497
#define TRAINER_ERNEST_3                    498
#define TRAINER_ERNEST_4                    499
#define TRAINER_ERNEST_5                    500
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN_1                     512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_EDWIN_2                     515
#define TRAINER_EDWIN_3                     516
#define TRAINER_EDWIN_4                     517
#define TRAINER_EDWIN_5                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_PRIMROSE_MEADOW    520
#define TRAINER_BRENDAN_CORALGROVE_ELEVATOR    521
#define TRAINER_BRENDAN_ROUTE_11_NORMAL    522
#define TRAINER_BRENDAN_ROUTE_11_ANGRY   523
#define TRAINER_BRENDAN_BASALEK_TOWN   524
#define TRAINER_UNUSED_525_   525
#define TRAINER_UNUSED_526_   526
#define TRAINER_UNUSED_527_   527
#define TRAINER_UNUSED_528_   528
#define TRAINER_MAY_PRIMROSE_MEADOW        529
#define TRAINER_MAY_CORALGROVE_ELEVATOR        530
#define TRAINER_MAY_ROUTE_11_NORMAL        531
#define TRAINER_MAY_ROUTE_11_ANGRY       532
#define TRAINER_MAY_BASALEK_TOWN       533
#define TRAINER_UNUSED_534_       534
#define TRAINER_UNUSED_535_       535
#define TRAINER_UNUSED_536_       536
#define TRAINER_UNUSED_537_       537
#define TRAINER_ISAAC_1                     538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_ISAAC_2                     541
#define TRAINER_ISAAC_3                     542
#define TRAINER_ISAAC_4                     543
#define TRAINER_ISAAC_5                     544
#define TRAINER_LYDIA_1                     545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_LYDIA_2                     548
#define TRAINER_LYDIA_3                     549
#define TRAINER_LYDIA_4                     550
#define TRAINER_LYDIA_5                     551
#define TRAINER_R7_NINJABOYSON_1                   552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_R7_NINJABOYSON_2                   555
#define TRAINER_R7_NINJABOYSON_3                   556
#define TRAINER_R7_NINJABOYSON_4                   557
#define TRAINER_R7_NINJABOYSON_5                   558
#define TRAINER_CATHERINE_1                 559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_CATHERINE_2                 562
#define TRAINER_CATHERINE_3                 563
#define TRAINER_CATHERINE_4                 564
#define TRAINER_CATHERINE_5                 565
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_UNUSED_592_    592
#define TRAINER_UNUSED_593_     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_UNUSED_599_    599
#define TRAINER_UNUSED_600_         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY_1                     604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_HALEY_2                     607
#define TRAINER_HALEY_3                     608
#define TRAINER_HALEY_4                     609
#define TRAINER_HALEY_5                     610
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES_1                     621
#define TRAINER_JAMES_2                     622
#define TRAINER_JAMES_3                     623
#define TRAINER_JAMES_4                     624
#define TRAINER_JAMES_5                     625
#define TRAINER_BRICE                       626
#define TRAINER_TRENT_1                     627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS_1                     629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_LUCAS_2                     633
#define TRAINER_MIKE_1                      634
#define TRAINER_MIKE_2                      635
#define TRAINER_TRENT_2                     636
#define TRAINER_TRENT_3                     637
#define TRAINER_TRENT_4                     638
#define TRAINER_TRENT_5                     639
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN_1              642
#define TRAINER_KIRA_AND_DAN_2              643
#define TRAINER_KIRA_AND_DAN_3              644
#define TRAINER_KIRA_AND_DAN_4              645
#define TRAINER_KIRA_AND_DAN_5              646
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_UNUSED_661_     661
#define TRAINER_UNUSED_662_    662
#define TRAINER_UNUSED_663_    663
#define TRAINER_UNUSED_664_         664
#define TRAINER_UNUSED_665_        665
#define TRAINER_UNUSED_666_        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI_1                      672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY_1              681
#define TRAINER_JOHN_AND_JAY_2              682
#define TRAINER_JOHN_AND_JAY_3              683
#define TRAINER_JOHN_AND_JAY_4              684
#define TRAINER_JOHN_AND_JAY_5              685
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY_1              687
#define TRAINER_LILA_AND_ROY_2              688
#define TRAINER_LILA_AND_ROY_3              689
#define TRAINER_LILA_AND_ROY_4              690
#define TRAINER_LILA_AND_ROY_5              691
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DESERT_HIKER3DRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_UNUSED_768_        768
#define TRAINER_UNUSED_769_        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_CASUAL_IRIS                      802
#define TRAINER_LEADER_DRAYDEN                      803
#define TRAINER_ELITE_FOUR_MINA                      804
#define TRAINER_MINA                        TRAINER_ELITE_FOUR_MINA
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_EMERALD     855
#define MAX_TRAINERS_COUNT_EMERALD 864

#if IS_FRLG
#define TRAINERS_COUNT                      TRAINERS_COUNT_FRLG
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_FRLG
#else
#define TRAINERS_COUNT                      TRAINERS_COUNT_EMERALD
#define MAX_TRAINERS_COUNT                  MAX_TRAINERS_COUNT_EMERALD
#endif
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
