SandstoneCity_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, VisitedSandstone
	.byte 0


VisitedSandstone::
	setflag FLAG_VISITED_SANDSTONE_CITY
	end


Sandstone_Sign1::
	msgbox Sandstone_Sign1_Text, MSGBOX_SIGN
	end


Sandstone_Sign2::
	msgbox Sandstone_Sign2_Text, MSGBOX_SIGN
	end


Sandstone_Sign3::
	msgbox Sandstone_Sign3_Text, MSGBOX_SIGN
	end


Sandstone_Sign4::
	msgbox Sandstone_Sign4_Text, MSGBOX_SIGN
	end


Sandstone_Sign5::
	msgbox Sandstone_Sign5_Text, MSGBOX_SIGN
	end


Sandstone_Sign6::
	msgbox Sandstone_Sign6_Text, MSGBOX_SIGN
	end


Sandstone_Boy2::
	msgbox Sandstone_Boy2_Text, MSGBOX_NPC
	end


Sandstone_Lass::
	msgbox Sandstone_Lass_Text, MSGBOX_NPC
	end


Sandstone_OldMan::
	msgbox Sandstone_OldMan_Text, MSGBOX_NPC
	end


Sandstone_GameboyKid1::
	msgbox Sandstone_GameboyKid1_Text, MSGBOX_NPC
	end


Sandstone_GameboyKid2::
	msgbox Sandstone_GameboyKid2_Text, MSGBOX_NPC
	end


Sandstone_GossipWoman1::
	msgbox Sandstone_GossipWoman1_Text, MSGBOX_NPC
	end


Sandstone_GossipWoman2::
	msgbox Sandstone_GossipWoman2_Text, MSGBOX_NPC
	end


Sandstone_Gentleman::
	msgbox Sandstone_Gentleman_Text, MSGBOX_NPC
	end


Sandstone_Maniac::
	msgbox Sandstone_Maniac_Text, MSGBOX_NPC
	end


Sandstone_Man3::
	msgbox Sandstone_Man3_Text, MSGBOX_NPC
	end


Sandstone_Man5::
	msgbox Sandstone_Man5_Text, MSGBOX_NPC
	end


Sandstone_Sign1_Text::
	.string "$"

Sandstone_Sign2_Text::
	.string "$"

Sandstone_Sign3_Text::
	.string "$"

Sandstone_Sign4_Text::
	.string "$"

Sandstone_Sign5_Text::
	.string "$"

Sandstone_Sign6_Text::
	.string "$"

Sandstone_Boy2_Text::
	.string "$"

Sandstone_Lass_Text::
	.string "$"

Sandstone_OldMan_Text::
	.string "$"

Sandstone_GameboyKid1_Text::
	.string "$"

Sandstone_GameboyKid2_Text::
	.string "$"

Sandstone_GossipWoman1_Text::
	.string "$"

Sandstone_GossipWoman2_Text::
	.string "$"

Sandstone_Gentleman_Text::
	.string "$"

Sandstone_Maniac_Text::
	.string "$"

Sandstone_Man3_Text::
	.string "$"

Sandstone_Man5_Text::
	.string "$"
