AldeleafMart_MapScripts::
	.byte 0


Aldeleaf_Mart_EventScript_BlackBelt::
# 4 "data/maps/AldeleafMart/scripts.pory"
	msgbox Aldeleaf_Mart_Text_SomeItemsOnlyAtMart, MSGBOX_NPC
	end


Aldeleaf_Mart_EventScript_Man::
# 8 "data/maps/AldeleafMart/scripts.pory"
	msgbox Aldeleaf_Mart_Text_GreatBallIsBetter, MSGBOX_NPC
	end


Aldeleaf_Mart_Text_SomeItemsOnlyAtMart::
# 11 "data/maps/AldeleafMart/scripts.pory"
	.string "Do you use repels?\n"
	.string "They keep Pokémon away, so they're\l"
	.string "useful when you're in a hurry.$"

Aldeleaf_Mart_Text_GreatBallIsBetter::
# 16 "data/maps/AldeleafMart/scripts.pory"
	.string "Did you know that most marts\n"
	.string "sell the same items?\p"
	.string "It doesn't matter if you're\n"
	.string "visiting Aldeleaf or Coralgrove,\l"
	.string "you should be able to find\l"
	.string "the same range of products.$"
