AldeleafMart_MapScripts::
	.byte 0


Aldeleaf_Mart_EventScript_BlackBelt::
	msgbox Aldeleaf_Mart_Text_SomeItemsOnlyAtMart, MSGBOX_NPC
	end


Aldeleaf_Mart_EventScript_Man::
	msgbox Aldeleaf_Mart_Text_GreatBallIsBetter, MSGBOX_NPC
	end


Aldeleaf_Mart_Text_SomeItemsOnlyAtMart::
	.string "Do you use repels?\n"
	.string "They keep Pokémon away, so they're\l"
	.string "useful when you're in a hurry.$"

Aldeleaf_Mart_Text_GreatBallIsBetter::
	.string "I was hoping to find Great Balls here\n"
	.string "but it seems this mart's selection\l"
	.string "is a bit limited…$"
