Route28TunnelHouse_MapScripts::
	.byte 0


Route28TH_Announcer::
# 4 "data/maps/Route28TunnelHouse/scripts.pory"
	msgbox Route28TH_Announcer_Text, MSGBOX_NPC
	end


Route28TH_Hiker::
# 8 "data/maps/Route28TunnelHouse/scripts.pory"
	msgbox Route28TH_Hiker_Text, MSGBOX_NPC
	end


Route28TH_Lass::
# 12 "data/maps/Route28TunnelHouse/scripts.pory"
	msgbox Route28TH_Lass_Text, MSGBOX_NPC
	end


Route28TH_OldMan::
# 16 "data/maps/Route28TunnelHouse/scripts.pory"
	msgbox Route28TH_OldMan_Text, MSGBOX_NPC
	end


Route28TH_OldWoman::
# 20 "data/maps/Route28TunnelHouse/scripts.pory"
	msgbox Route28TH_OldWoman_Text, MSGBOX_NPC
	end


Route28TH_Announcer_Text::
# 24 "data/maps/Route28TunnelHouse/scripts.pory"
	.string "I'm sorry, but there has been an\n"
	.string "avalance higher up the route.\p"
	.string "As a precaution, all travel through\n"
	.string "the gate tunnel is currently prohibited.$"

Route28TH_Hiker_Text::
# 30 "data/maps/Route28TunnelHouse/scripts.pory"
	.string "Not even us experienced hikers\n"
	.string "are allowed to pass.\p"
	.string "I understand their decision though.\n"
	.string "The terrain is very unstable and\l"
	.string "often times when an avalanche occurs,\l"
	.string "another one will not be far behind.$"

Route28TH_Lass_Text::
# 38 "data/maps/Route28TunnelHouse/scripts.pory"
	.string "I was on my way to meet my boyfriend\n"
	.string "who lives in Iceperch City!\l"
	.string "What do I do now?!$"

Route28TH_OldMan_Text::
# 43 "data/maps/Route28TunnelHouse/scripts.pory"
	.string "These avalanches have been occurring\n"
	.string "for as long as I can remember.\p"
	.string "I do wonder though, are they a natural\n"
	.string "occurrence, or perhaps caused by some\l"
	.string "unknown Pokémon?$"

Route28TH_OldWoman_Text::
# 50 "data/maps/Route28TunnelHouse/scripts.pory"
	.string "This gate tunnel helps people cross\n"
	.string "some very perilous rocky terrain.\p"
	.string "There have been proposals to extend it\n"
	.string "all the way to Iceperch City,\l"
	.string "but unfortunately no building can\l"
	.string "withstand the unpredictable power of\l"
	.string "an avalanche.$"
