Route9_MapScripts::
	.byte 0


Route9_Tr1_Swimmer_M::
	trainerbattle_single TRAINER_R9_TR1_SWIMMER_M, R9Tr1_Intro, R9Tr1_Lose
	msgbox R9Tr1_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr2_BlackBelt::
	trainerbattle_single TRAINER_R9_TR2_BLACKBELT, R9Tr2_Intro, R9Tr2_Lose
	msgbox R9Tr2_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr3_BirdKeeper::
	trainerbattle_single TRAINER_R9_TR3_BIRDKEEPER, R9Tr3_Intro, R9Tr3_Lose
	msgbox R9Tr3_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr4_BattleGirl::
	trainerbattle_single TRAINER_R9_TR4_BATTLEGIRL, R9Tr4_Intro, R9Tr4_Lose
	msgbox R9Tr4_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr5_Swimmer_F::
	trainerbattle_single TRAINER_R9_TR5_SWIMMER_F, R9Tr5_Intro, R9Tr5_Lose
	msgbox R9Tr5_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr6_Fisherman::
	trainerbattle_single TRAINER_R9_TR6_FISHERMAN, R9Tr6_Intro, R9Tr6_Lose
	msgbox R9Tr6_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr7_Hiker::
	trainerbattle_single TRAINER_R9_TR7_HIKER, R9Tr7_Intro, R9Tr7_Lose
	msgbox R9Tr7_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr8_Collector::
	trainerbattle_single TRAINER_R9_TR8_COLLECTOR, R9Tr8_Intro, R9Tr8_Lose
	msgbox R9Tr8_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr9_Swimmer_M2::
	trainerbattle_single TRAINER_R9_TR9_SWIMMER_M2, R9Tr9_Intro, R9Tr9_Lose
	msgbox R9Tr9_PostBattle, MSGBOX_AUTOCLOSE
	end


Route9_Tr10_LandSwimmer::
	trainerbattle_single TRAINER_R9_TR10_LANDSWIMMER, R9Tr10_Intro, R9Tr10_Lose
	msgbox R9Tr10_PostBattle, MSGBOX_AUTOCLOSE
	end


R9Tr1_Intro::
	.string "$"

R9Tr1_Lose::
	.string "$"

R9Tr1_PostBattle::
	.string "$"

R9Tr2_Intro::
	.string "$"

R9Tr2_Lose::
	.string "$"

R9Tr2_PostBattle::
	.string "$"

R9Tr3_Intro::
	.string "$"

R9Tr3_Lose::
	.string "$"

R9Tr3_PostBattle::
	.string "$"

R9Tr4_Intro::
	.string "$"

R9Tr4_Lose::
	.string "$"

R9Tr4_PostBattle::
	.string "$"

R9Tr5_Intro::
	.string "$"

R9Tr5_Lose::
	.string "$"

R9Tr5_PostBattle::
	.string "$"

R9Tr6_Intro::
	.string "$"

R9Tr6_Lose::
	.string "$"

R9Tr6_PostBattle::
	.string "$"

R9Tr7_Intro::
	.string "$"

R9Tr7_Lose::
	.string "$"

R9Tr7_PostBattle::
	.string "$"

R9Tr8_Intro::
	.string "$"

R9Tr8_Lose::
	.string "$"

R9Tr8_PostBattle::
	.string "$"

R9Tr9_Intro::
	.string "$"

R9Tr9_Lose::
	.string "$"

R9Tr9_PostBattle::
	.string "$"

R9Tr10_Intro::
	.string "$"

R9Tr10_Lose::
	.string "$"

R9Tr10_PostBattle::
	.string "$"
