Sandstone_Library_2F_MapScripts::
	.byte 0


PutTheBookBack::
	.string "{PLAYER} put the book back.$"

Book1Intro::
	.string "This book is titled “Sinnoh\n"
	.string "Myth.” Want to read it?$"

Book1::
	.string "“Sinnoh Myth”\p"
	.string "Betray not your anger, lest ??? will\n"
	.string "come.\p"
	.string "Weep not with sorrow, or ??? will\n"
	.string "draw near.\p"
	.string "When joy and enjoyment come natural\n"
	.string "as the very air, that is happiness.\p"
	.string "Let such be blessed by the hand\n"
	.string "of Master ???.\p"
	.string "Those words were spoken often\n"
	.string "as customary.$"

Book2Intro::
	.string "This book is titled “Sinnoh Region's\n"
	.string "Mythology.” Want to read it?$"

Book2::
	.string "“Sinnoh Region's Mythology”\p"
	.string "Long ago, when Sinnoh had just been\n"
	.string "made, Pokémon and humans led\l"
	.string "separate lives.\p"
	.string "That is not to say they did not help\n"
	.string "each other. No, indeed they did.\p"
	.string "They supplied each other with goods,\n"
	.string "and supported each other.\p"
	.string "A Pokémon proposed to the others\n"
	.string "to always be ready to help humans.\p"
	.string "It asked that Pokémon be ready to\n"
	.string "appear before humans always.\p"
	.string "Thus, to this day, Pokémon appear\n"
	.string "to us if we venture into tall grass.$"

Book3Intro::
	.string "This book is titled “Sinnoh's\n"
	.string "Myth.” Want to read it?$"

Book3::
	.string "“Sinnoh's Myth”\p"
	.string "Three Pokémon there were.\p"
	.string "Into the lakes they dove.\n"
	.string "Deep, deep, drawing no breath.\p"
	.string "Deeper, deeper they dove.\n"
	.string "Into suffocating depths they dove.\p"
	.string "Deeper, then deepest they alight.\n"
	.string "From the lake floor they rise.\p"
	.string "Bearing with them the power to make\n"
	.string "vast lands, they rise again.$"

Book4Intro::
	.string "This book is titled “Veilstone's\n"
	.string "Myth.” Want to read it?$"

Book4Part1::
	.string "“Veilstone's Myth”\p"
	.string "A young man, callow and foolish in\n"
	.string "innocence, came to own a sword.\p"
	.string "With it, he smote Pokémon, which gave\n"
	.string "sustenance, with carefree abandon.\p"
	.string "Those not taken as food, he\n"
	.string "discarded, with no afterthought.\p"
	.string "The following year, no Pokémon\n"
	.string "appeared. Larders grew bare.\p"
	.string "…Would you like to keep reading?$"

Book4Part2::
	.string "The young man, seeking the missing\n"
	.string "Pokémon, journeyed afar.\p"
	.string "Long did he search. And far and wide,\n"
	.string "too, until one he did find.\p"
	.string "Asked he, “Why do you hide?”\n"
	.string "To which the Pokémon replied…\p"
	.string "“If you bear your sword to bring\n"
	.string "harm upon us, with claws and\l"
	.string "fangs, we will exact a toll.\p"
	.string "“From your kind we will take our\n"
	.string "toll, for it must be done.\p"
	.string "“Done it must be to guard ourselves\n"
	.string "and for it, I apologize.”\p"
	.string "…Would you like to keep reading?$"

Book4Part3::
	.string "To the skies, the young man shouted\n"
	.string "his dismay.\p"
	.string "“In having found the sword, I have\n"
	.string "lost so much.\p"
	.string "“Gorged with power, I grew blind\n"
	.string "to Pokémon being alive.\p"
	.string "“I will never fall savage again.\n"
	.string "This sword I denounce and forsake.\p"
	.string "“I plead for forgiveness,\n"
	.string "for I was but a fool.”\p"
	.string "So saying, the young man hurled the\n"
	.string "sword to the ground, snapping it.\p"
	.string "Seeing this, the Pokémon disappeared\n"
	.string "to a place beyond seeing…$"

Book5Intro::
	.string "This ancient book is titled “The\n"
	.string "Original Story.” Want to read it?$"

Book5Part1::
	.string "In the beginning, there was only\n"
	.string "a churning turmoil of chaos.\p"
	.string "At the heart of chaos, where all\n"
	.string "things became one, appeared an Egg.\p"
	.string "Having tumbled from the vortex, the\n"
	.string "Egg gave rise to the Original One.\p"
	.string "…Would you like to keep reading?$"

Book5Part2::
	.string "From itself, two beings the Original\n"
	.string "One did make.\p"
	.string "Time started to spin.\n"
	.string "Space began to expand.\p"
	.string "From itself again, three living things\n"
	.string "the Original One did make.\p"
	.string "…Would you like to keep reading?$"

Book5Part3::
	.string "The two beings wished, and from them,\n"
	.string "matter came to be.\p"
	.string "The three living things wished, and\n"
	.string "from them, spirit came to be.\p"
	.string "The world created, the Original One\n"
	.string "took to unyielding sleep…$"

Book6Intro::
	.string "This book is titled “A Horrific\n"
	.string "Myth.” Want to read it?$"

Book6::
	.string "Look not into the Pokémon's eyes.\p"
	.string "In but an instant, you'll have no\n"
	.string "recollection of who you are.\p"
	.string "Return home, but how?\n"
	.string "When there is nothing to remember?\p"
	.string "Dare not touch the Pokémon's body.\p"
	.string "In but three short days, all emotions\n"
	.string "will drain away.\p"
	.string "Above all, above all, harm not\n"
	.string "the Pokémon.\p"
	.string "In a scant five days, the offender\n"
	.string "will grow immobile in entirety.$"

Book7Intro::
	.string "This book is titled “Sinnoh Folk\n"
	.string "Stories.”\p$"

Book7Story1::
	.string "“Sinnoh Folk Story 1”\p"
	.string "Pick clean the bones of Pokémon\n"
	.string "caught in the sea or stream.\p"
	.string "Thank them for the meals they\n"
	.string "provide, and pick their bones clean.\p"
	.string "When the bones are as clean as can\n"
	.string "be, set them free in the water from\l"
	.string "which they came.\p"
	.string "The Pokémon will return, fully\n"
	.string "fleshed, and it begins anew.$"

Book7Story2::
	.string "“Sinnoh Folk Story 2”\p"
	.string "There lived a Pokémon in a forest.\p"
	.string "In the forest, the Pokémon shed its\n"
	.string "hide to sleep as a human.\p"
	.string "Awakened, the human dons the\n"
	.string "Pokémon hide to roam villages.$"

Book7Story3::
	.string "“Sinnoh Folk Story 3”\p"
	.string "There once were Pokémon that\n"
	.string "became very close to humans.\p"
	.string "There once were humans and Pokémon\n"
	.string "that ate together at the same table.\p"
	.string "It was a time when there existed no\n"
	.string "differences to distinguish the two.$"

BooksOnThisFloor::
	.string "On this floor, you will find many\n"
	.string "books on the myths and legends of\l"
	.string "the Sinnoh region.$"

bookideas::
	.string "book about the 3 birds looking for high perch to roost, use for shadow lugia"
	.string "book about how the 3 failed their mission, after which they left the world in shame. it is said that a fragment of their spirit"
	.string "remained in our world and people built a beacon in case of their potential return"
	.string "book about little green men$"
